### PR TITLE
Add toggle option to button

### PR DESCRIPTION
**Pull request by richardwilliamson**
I haven’t been able to get QT working and am about to get on a plane - but I’d be interested to know how wrong I’ve got this - expected behaviour is that if toggle mode is selected for a button, the first press will send the max command, the second send the min. I’m not sure how persistence works so something may need to be added to save this to the file!

I probably should have avoided committing the Xcode project as that will probably break at the other end..

### CODE REVIEW

**Comment by MizPlusPlus** [comment]
Hey Richard,

Thanks for this great idea!  I think I instead of merging in this pull request, I will just enable the Min/Max 2 fields for buttons, and you can specify the toggle behavior that way.  I'll try to get that in soon...

~Chris

**Comment by richardwilliamson** [comment]
Thanks! Only issue I can see is there are times that you only want the receiver to receive one message on button press - at the moment I believe the widget will always send two messages (min on down, max on up) - devices that ignore the argument (say qlab/cue/fire) would end up firing twice I think (although I may be wrong) - I may be talking rubbish and you may have done this already, but ideally if min and max are the same the button would only send the message once, but I'm not totally clear how this would work with a toggle

**Comment by MizPlusPlus** [comment]
Currently, if you leave Min blank and fill in a number for Max, then only Max is sent on the button down press.  (same if you leave Max blank and fill in Min)

So, to make a toggle button, you would just fill in Max and Max2 and leave Min and Min2 blank.

And, then you'd have he bonus option of filling in all 4 fields to get a toggle button with both edges - if desired.

**Comment by richardwilliamson** [comment]
Ah brilliant! I hadn't realised you could keep a value blank!

**Comment by MizPlusPlus** [comment]
I'll add better help notes when I make this change too ;)

**Comment by richardwilliamson** [comment]
Sorry, one other thing - will the UI be able to give feedback on the toggle state, it would be good to have two colour fields If possible (both for this and also some other widgets) - an up and a down value. I suppose a button should have an option for the state change to be locally driven (from the action of the press) or driven via remote feedback (so the colour only changes when the server says it has) 

Also - does the min/max accept string values? It would be useful if you could send strings "on" and "off" or similar in certain use cases!

**Comment by MizPlusPlus** [comment]
Hey Richard,

Just released v0.4.  It has the Toggle button support, which includes separate colors (or icons) for the toggled state.  Buttons can also now send strings like "on" and "off"

~Chris

**Pull request closed without merging**
